### ISSUE TITLE
 Implement Type of Person into Contact views and table

### ISSUE THREAD

**Issue by damuz91** [GLXI/sugarcrm-glx#6]
Type of person should.
Select with Sector > Subsector > Industry > Subindustry and Type of Entity.
Contact should have the subindustry id and the type of entity id. The subindustry depends on the hierarchy described above. The type of entity depends on the selected subindustry.

**Comment by damuz91** [comment]
@cgomezru Should populate the tables

**Comment by webesteban** [comment]
issue solved with commit [Type of person](https://github.com/GLXI/sugarcrm-glx/commit/eddf713ed7a4be37cd8105e1ce0aa06940bb77d2)

**Comment by webesteban** [comment]
15e747e44dac11da4f88ea6674fdb624c0404677
