### ISSUE TITLE
Account Hierarchy

### ISSUE THREAD

**Issue by damuz91** [GLXI/sugarcrm-glx#9]
Should implement an account hierarchy where an account can have assigned another account as its parent. Also display a hierarchy view for it to display the entire hierarchy linking.

![captura de pantalla 2017-02-24 a las 12 25 58 p m](https://cloud.githubusercontent.com/assets/2810042/23313647/9067d8ba-fa8c-11e6-9748-e258910fdb7e.png)

**Comment by lca85** [comment]
Done here 033b8b58
